export const SITE_SEO = {
  siteName: "LeadyIA",
  baseUrl: "https://leadyia.com",
  defaultLocale: "pt_BR",
  themeColor: "#0F172A",
  defaultImage: "/og-image.png",
  logo: "/android-chrome-512x512.png",
  author: "LeadyIA",
  twitterHandle: "@leadyia",
  titleTemplate: "%s | LeadyIA",
  defaultTitle: "LeadyIA — IA Comercial para Empresas | Chatbot com IA, WhatsApp, Agenda e Vendas",
  defaultDescription:
    "Automatize atendimento, vendas e captação de clientes com IA. Chatbot inteligente para clínicas, imobiliárias, advocacia, educação, estética, e-commerce e empresas. Agende consultas, gere Pix, qualifique leads e aumente suas conversões.",
  defaultKeywords: [
    "chatbot IA",
    "inteligência artificial",
    "chatbot para empresas",
    "chatbot whatsapp",
    "assistente virtual",
    "automação comercial",
    "geração de leads",
    "qualificação de leads",
    "agenda automática",
    "pix automático",
    "chatbot imobiliária",
    "chatbot clínica",
    "chatbot advocacia",
    "chatbot educação",
    "chatbot ecommerce",
    "IA para vendas",
    "CRM IA",
    "automação atendimento",
    "IA para atendimento",
    "chatbot inteligente",
    "chatbot para empresas",
    "assistente virtual IA",
    "recepcionista virtual",
    "automação comercial",
    "automação de vendas",
    "chatbot whatsapp",
    "chatbot instagram",
    "chatbot para site",
    "RAG",
    "CRM com IA",
    "inteligência artificial para vendas",
    "automação de atendimento",
    "chatbot ecommerce",
    "chatbot clínica",
    "chatbot imobiliária",
    "chatbot jurídico",
    "chatbot educação",
    "leadyia"
  ],
  languages: [
    { locale: "pt-BR", hreflang: "pt-BR", pathPrefix: "" },
    { locale: "en-US", hreflang: "en-US", pathPrefix: "/en" },
    { locale: "es-ES", hreflang: "es-ES", pathPrefix: "/es" }
  ]
};
