import fs from 'node:fs';
const read=(f)=>fs.readFileSync(new URL(`../${f}`, import.meta.url),'utf8');
const home=read('src/pages/LeadyIAHighConversionLanding.jsx');
const routes=read('src/app/Routes.jsx');
const niches=read('src/data/verticalNiches.v1103_123.js');
const intl=read('src/config/international.config.js');
const checks=[];
const ok=(name, cond)=>{ if(!cond) throw new Error(`FAIL: ${name}`); checks.push(name); };
ok('14 commercial niches', (niches.match(/key:/g)||[]).length >= 14);
for (const path of ['/clinica','/estetica','/imobiliaria','/advocacia','/educacao','/ecommerce','/saas','/dentista','/veterinaria','/contabilidade','/automotivo','/restaurante','/fitness','/servicos-residenciais']) ok(`route ${path}`, routes.includes(`path="${path}"`));
ok('SaaS dedicated landing', routes.includes('path="/saas" element={<SaasLeadyiaLanding />}'));
ok('Business Profile conversion section', home.includes('id="business-profile"'));
ok('WhatsApp real section', home.includes('id="whatsapp-real"'));
ok('fail closed marketing contract', home.includes('não deve inventá-la'));
ok('no fabricated testimonials block', !home.includes('Cliente LeadyIA</strong>'));
ok('source attribution v206', home.includes('leadyia_main_v1103_206'));
for (const c of ['BR','US','PT','ES','GB','CA','MX','CL','CO','AR','PE']) ok(`country ${c}`, intl.includes(`code: "${c}"`));
ok('Brazil Mercado Pago', /code: "BR"[^\n]+provider: "mercadopago"/.test(intl));
ok('international Stripe', /code: "US"[^\n]+provider: "stripe"/.test(intl));
console.log(`Landing Commercial Conversion v1103.206 — ${checks.length} checks OK`);
